class LoginError(Exception):
    pass


class SignupError(Exception):
    pass
